#!/bin/sh
git --work-tree=/var/www/treehouse --git-dir=/var/repo/treehouse checkout -f

#install dependencies
npm i --prefix /var/www/treehouse

#stop all instances of app with pm2
pm2 stop treehouse
pm2 start /var/www/treehouse/app.js --name treehouse -- --prod